version: "3.8"

services:
  php_wallet_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_wallet_app
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html
      - ./database:/var/www/database
    restart: unless-stopped
